/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author mhpolymath
 */
public class coach_panel extends javax.swing.JPanel {

    /**
     * Creates new form coach_panel
     */
    public coach_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlpn_tableCoach = new javax.swing.JScrollPane();
        jtable_member = new javax.swing.JTable();
        label_coachesTable = new javax.swing.JLabel();
        btn_coachInsert = new javax.swing.JButton();
        btn_coachDelete = new javax.swing.JButton();
        btn_updateCoaches = new javax.swing.JButton();
        btn_resetFilterCoach = new javax.swing.JButton();
        txt_filterLastNameCoachTable = new javax.swing.JTextField();
        txt_filterFirstNameCoachTable = new javax.swing.JTextField();
        label_firstNameFilterCoachtbl = new javax.swing.JLabel();
        label_lastNameFilterCoachtbl = new javax.swing.JLabel();
        btn_confirmFilterCoachtbl = new javax.swing.JButton();

        jtable_member.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jtable_member.setModel(new MemberTable().loadTable()
        );
        jtable_member.setDefaultEditor(Object.class,null);
        setupTableListener();
        jtable_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_memberMouseClicked(evt);
            }
        });
        scrlpn_tableCoach.setViewportView(jtable_member);

        label_coachesTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_coachesTable.setText("Coaches");

        btn_coachInsert.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_coachInsert.setText("Insert");
        btn_coachInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coachInsertMouseClicked(evt);
            }
        });
        btn_coachInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coachInsertActionPerformed(evt);
            }
        });

        btn_coachDelete.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_coachDelete.setText("Delete");
        btn_coachDelete.setEnabled(false);
        btn_coachDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coachDeleteMouseClicked(evt);
            }
        });
        btn_coachDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coachDeleteActionPerformed(evt);
            }
        });

        btn_updateCoaches.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_updateCoaches.setText("Update");
        btn_updateCoaches.setEnabled(false);
        btn_updateCoaches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateCoachesMouseClicked(evt);
            }
        });
        btn_updateCoaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateCoachesActionPerformed(evt);
            }
        });

        btn_resetFilterCoach.setText("Reset Filter");
        btn_resetFilterCoach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetFilterCoachMouseClicked(evt);
            }
        });
        btn_resetFilterCoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFilterCoachActionPerformed(evt);
            }
        });

        txt_filterLastNameCoachTable.setToolTipText("Enter last name");
        txt_filterLastNameCoachTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterLastNameCoachTableActionPerformed(evt);
            }
        });

        txt_filterFirstNameCoachTable.setToolTipText("Enter first name");
        txt_filterFirstNameCoachTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterFirstNameCoachTableActionPerformed(evt);
            }
        });

        label_firstNameFilterCoachtbl.setText("First Name");

        label_lastNameFilterCoachtbl.setText("Last Name");

        btn_confirmFilterCoachtbl.setText("Filter");
        btn_confirmFilterCoachtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmFilterCoachtblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_coachDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_coachInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_updateCoaches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_coachesTable)
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrlpn_tableCoach, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filterFirstNameCoachTable, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_firstNameFilterCoachtbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filterLastNameCoachTable, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_confirmFilterCoachtbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_resetFilterCoach))
                            .addComponent(label_lastNameFilterCoachtbl))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstNameFilterCoachtbl)
                    .addComponent(label_lastNameFilterCoachtbl))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filterLastNameCoachTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFilterCoach)
                    .addComponent(txt_filterFirstNameCoachTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmFilterCoachtbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_coachesTable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_coachInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlpn_tableCoach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_coachDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_updateCoaches, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_memberMouseClicked

    }//GEN-LAST:event_jtable_memberMouseClicked

    private void btn_coachInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coachInsertMouseClicked

    }//GEN-LAST:event_btn_coachInsertMouseClicked

    private void btn_coachInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coachInsertActionPerformed
        clearInsertFormTextFields();
        jframe_insertMember.setVisible(true);
    }//GEN-LAST:event_btn_coachInsertActionPerformed

    private void btn_coachDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coachDeleteMouseClicked
        if(!btn_memberDelete.isEnabled())
        return;
        int selectedRow = jtable_member.getSelectedRow();
        if(selectedRow == -1)
        return;

        Integer memberID = (Integer)jtable_member.getValueAt(selectedRow, 0);

        try{
            int result = new MemberTable().delete(new Member(memberID));
            if(result == 1){
                DatabaseOperation.showSuccessMessage(panel_member,"Member deleted successfully.");
                jtable_member.setModel(new MemberTable().loadTable());

            }
            else
            DatabaseOperation.showErrorMessage(panel_member,"Delete failed.");
        }
        catch(java.sql.SQLException e){
            DatabaseOperation.showErrorMessage(panel_member,e.getMessage());
        }
    }//GEN-LAST:event_btn_coachDeleteMouseClicked

    private void btn_coachDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coachDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_coachDeleteActionPerformed

    private void btn_updateCoachesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateCoachesMouseClicked
        if(!btn_updateMember.isEnabled())
        return;
        if(jtable_member.getSelectedRow() == -1)
        return;

        fillUpdateFieldsWithOldData();
        jframe_updateMember.setVisible(true);
    }//GEN-LAST:event_btn_updateCoachesMouseClicked

    private void btn_updateCoachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateCoachesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateCoachesActionPerformed

    private void btn_resetFilterCoachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetFilterCoachMouseClicked
        jtable_member.setModel(new MemberTable().loadTable());
        txt_filterFirstNameMemberTable.setText("");
        txt_filterLastNameMemberTable.setText("");
    }//GEN-LAST:event_btn_resetFilterCoachMouseClicked

    private void btn_resetFilterCoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFilterCoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterCoachActionPerformed

    private void txt_filterLastNameCoachTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterLastNameCoachTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterLastNameCoachTableActionPerformed

    private void txt_filterFirstNameCoachTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterFirstNameCoachTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterFirstNameCoachTableActionPerformed

    private void btn_confirmFilterCoachtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmFilterCoachtblMouseClicked
        String fname = txt_filterFirstNameMemberTable.getText();
        String lname = txt_filterLastNameMemberTable.getText();

        jtable_member.setModel(new MemberTable().selectByMemberName(new Member(null,fname,lname,null)));
    }//GEN-LAST:event_btn_confirmFilterCoachtblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_coachDelete;
    private javax.swing.JButton btn_coachInsert;
    private javax.swing.JButton btn_confirmFilterCoachtbl;
    private javax.swing.JButton btn_resetFilterCoach;
    public javax.swing.JButton btn_updateCoaches;
    public javax.swing.JTable jtable_member;
    private javax.swing.JLabel label_coachesTable;
    private javax.swing.JLabel label_firstNameFilterCoachtbl;
    private javax.swing.JLabel label_lastNameFilterCoachtbl;
    public javax.swing.JScrollPane scrlpn_tableCoach;
    private javax.swing.JTextField txt_filterFirstNameCoachTable;
    private javax.swing.JTextField txt_filterLastNameCoachTable;
    // End of variables declaration//GEN-END:variables
}
