/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author mhpolymath
 */
public class workout_panel extends javax.swing.JPanel {

    /**
     * Creates new form workout_panel
     */
    public workout_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlpn_tableFitData1 = new javax.swing.JScrollPane();
        jtable_gym1 = new javax.swing.JTable();
        label_fitDataTable1 = new javax.swing.JLabel();
        btn_fitDataInsert1 = new javax.swing.JButton();
        btn_fitDataDelete1 = new javax.swing.JButton();
        btn_updateFitData1 = new javax.swing.JButton();
        btn_resetFilterFitData1 = new javax.swing.JButton();
        txt_filterHmmmm2FitDataTable1 = new javax.swing.JTextField();
        txt_filterHmmmFitDataTable1 = new javax.swing.JTextField();
        label_hmmmFilterFitDatatbl1 = new javax.swing.JLabel();
        label_Hmmmm2FilterFitDatatbl1 = new javax.swing.JLabel();
        btn_confirmFilterFitDatatbl1 = new javax.swing.JButton();

        jtable_gym1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jtable_gym1.setModel(new MemberTable().loadTable()
        );
        jtable_member.setDefaultEditor(Object.class,null);
        setupTableListener();
        jtable_gym1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_gym1MouseClicked(evt);
            }
        });
        scrlpn_tableFitData1.setViewportView(jtable_gym1);

        label_fitDataTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_fitDataTable1.setText("Fitness Records");

        btn_fitDataInsert1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_fitDataInsert1.setText("Insert");
        btn_fitDataInsert1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fitDataInsert1MouseClicked(evt);
            }
        });
        btn_fitDataInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fitDataInsert1ActionPerformed(evt);
            }
        });

        btn_fitDataDelete1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_fitDataDelete1.setText("Delete");
        btn_fitDataDelete1.setEnabled(false);
        btn_fitDataDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fitDataDelete1MouseClicked(evt);
            }
        });
        btn_fitDataDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fitDataDelete1ActionPerformed(evt);
            }
        });

        btn_updateFitData1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_updateFitData1.setText("Update");
        btn_updateFitData1.setEnabled(false);
        btn_updateFitData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateFitData1MouseClicked(evt);
            }
        });
        btn_updateFitData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateFitData1ActionPerformed(evt);
            }
        });

        btn_resetFilterFitData1.setText("Reset Filter");
        btn_resetFilterFitData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetFilterFitData1MouseClicked(evt);
            }
        });
        btn_resetFilterFitData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFilterFitData1ActionPerformed(evt);
            }
        });

        txt_filterHmmmm2FitDataTable1.setToolTipText("Enter last name");
        txt_filterHmmmm2FitDataTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterHmmmm2FitDataTable1ActionPerformed(evt);
            }
        });

        txt_filterHmmmFitDataTable1.setToolTipText("Enter first name");
        txt_filterHmmmFitDataTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterHmmmFitDataTable1ActionPerformed(evt);
            }
        });

        label_hmmmFilterFitDatatbl1.setText("hmmm");

        label_Hmmmm2FilterFitDatatbl1.setText("hmmmm2");

        btn_confirmFilterFitDatatbl1.setText("Filter");
        btn_confirmFilterFitDatatbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmFilterFitDatatbl1MouseClicked(evt);
            }
        });
        btn_confirmFilterFitDatatbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmFilterFitDatatbl1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_fitDataDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_fitDataInsert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_updateFitData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_fitDataTable1)
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrlpn_tableFitData1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filterHmmmFitDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_hmmmFilterFitDatatbl1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filterHmmmm2FitDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_confirmFilterFitDatatbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_resetFilterFitData1))
                            .addComponent(label_Hmmmm2FilterFitDatatbl1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hmmmFilterFitDatatbl1)
                    .addComponent(label_Hmmmm2FilterFitDatatbl1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filterHmmmm2FitDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFilterFitData1)
                    .addComponent(txt_filterHmmmFitDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmFilterFitDatatbl1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fitDataTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fitDataInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlpn_tableFitData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_fitDataDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_updateFitData1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_gym1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_gym1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtable_gym1MouseClicked

    private void btn_fitDataInsert1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fitDataInsert1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fitDataInsert1MouseClicked

    private void btn_fitDataInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fitDataInsert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fitDataInsert1ActionPerformed

    private void btn_fitDataDelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fitDataDelete1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fitDataDelete1MouseClicked

    private void btn_fitDataDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fitDataDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fitDataDelete1ActionPerformed

    private void btn_updateFitData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateFitData1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateFitData1MouseClicked

    private void btn_updateFitData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateFitData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateFitData1ActionPerformed

    private void btn_resetFilterFitData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetFilterFitData1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterFitData1MouseClicked

    private void btn_resetFilterFitData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFilterFitData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterFitData1ActionPerformed

    private void txt_filterHmmmm2FitDataTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterHmmmm2FitDataTable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterHmmmm2FitDataTable1ActionPerformed

    private void txt_filterHmmmFitDataTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterHmmmFitDataTable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterHmmmFitDataTable1ActionPerformed

    private void btn_confirmFilterFitDatatbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmFilterFitDatatbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmFilterFitDatatbl1MouseClicked

    private void btn_confirmFilterFitDatatbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmFilterFitDatatbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmFilterFitDatatbl1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmFilterFitDatatbl1;
    public javax.swing.JButton btn_fitDataDelete1;
    private javax.swing.JButton btn_fitDataInsert1;
    private javax.swing.JButton btn_resetFilterFitData1;
    public javax.swing.JButton btn_updateFitData1;
    public javax.swing.JTable jtable_gym1;
    private javax.swing.JLabel label_Hmmmm2FilterFitDatatbl1;
    private javax.swing.JLabel label_fitDataTable1;
    private javax.swing.JLabel label_hmmmFilterFitDatatbl1;
    public javax.swing.JScrollPane scrlpn_tableFitData1;
    private javax.swing.JTextField txt_filterHmmmFitDataTable1;
    private javax.swing.JTextField txt_filterHmmmm2FitDataTable1;
    // End of variables declaration//GEN-END:variables
}
