/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author mhpolymath
 */
public class gym_panel extends javax.swing.JPanel {

    /**
     * Creates new form gym_panel
     */
    public gym_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlpn_tableGym1 = new javax.swing.JScrollPane();
        jtable_gym1 = new javax.swing.JTable();
        label_gymTable1 = new javax.swing.JLabel();
        btn_gymInsert1 = new javax.swing.JButton();
        btn_gymDelete1 = new javax.swing.JButton();
        btn_updateGym1 = new javax.swing.JButton();
        btn_resetFilterGym1 = new javax.swing.JButton();
        txt_filterAddressGymTable1 = new javax.swing.JTextField();
        txt_filterNameGymTable1 = new javax.swing.JTextField();
        label_NameFilterGymtbl1 = new javax.swing.JLabel();
        label_AddressFilterGymtbl1 = new javax.swing.JLabel();
        btn_confirmFilterGymtbl1 = new javax.swing.JButton();

        jtable_gym1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jtable_gym1.setModel(new MemberTable().loadTable()
        );
        jtable_member.setDefaultEditor(Object.class,null);
        setupTableListener();
        jtable_gym1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_gym1MouseClicked(evt);
            }
        });
        scrlpn_tableGym1.setViewportView(jtable_gym1);

        label_gymTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_gymTable1.setText("Gym Branches");

        btn_gymInsert1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_gymInsert1.setText("Insert");
        btn_gymInsert1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gymInsert1MouseClicked(evt);
            }
        });
        btn_gymInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gymInsert1ActionPerformed(evt);
            }
        });

        btn_gymDelete1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_gymDelete1.setText("Delete");
        btn_gymDelete1.setEnabled(false);
        btn_gymDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gymDelete1MouseClicked(evt);
            }
        });
        btn_gymDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gymDelete1ActionPerformed(evt);
            }
        });

        btn_updateGym1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_updateGym1.setText("Update");
        btn_updateGym1.setEnabled(false);
        btn_updateGym1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateGym1MouseClicked(evt);
            }
        });
        btn_updateGym1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateGym1ActionPerformed(evt);
            }
        });

        btn_resetFilterGym1.setText("Reset Filter");
        btn_resetFilterGym1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetFilterGym1MouseClicked(evt);
            }
        });
        btn_resetFilterGym1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFilterGym1ActionPerformed(evt);
            }
        });

        txt_filterAddressGymTable1.setToolTipText("Enter last name");
        txt_filterAddressGymTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterAddressGymTable1ActionPerformed(evt);
            }
        });

        txt_filterNameGymTable1.setToolTipText("Enter first name");
        txt_filterNameGymTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterNameGymTable1ActionPerformed(evt);
            }
        });

        label_NameFilterGymtbl1.setText("Branch Name");

        label_AddressFilterGymtbl1.setText("Address");

        btn_confirmFilterGymtbl1.setText("Filter");
        btn_confirmFilterGymtbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmFilterGymtbl1MouseClicked(evt);
            }
        });
        btn_confirmFilterGymtbl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmFilterGymtbl1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_gymDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_gymInsert1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_updateGym1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_gymTable1)
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrlpn_tableGym1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filterNameGymTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_NameFilterGymtbl1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filterAddressGymTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_confirmFilterGymtbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_resetFilterGym1))
                            .addComponent(label_AddressFilterGymtbl1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_NameFilterGymtbl1)
                    .addComponent(label_AddressFilterGymtbl1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filterAddressGymTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFilterGym1)
                    .addComponent(txt_filterNameGymTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmFilterGymtbl1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gymTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gymInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlpn_tableGym1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_gymDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_updateGym1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_gym1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_gym1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtable_gym1MouseClicked

    private void btn_gymInsert1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gymInsert1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gymInsert1MouseClicked

    private void btn_gymInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gymInsert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gymInsert1ActionPerformed

    private void btn_gymDelete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gymDelete1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gymDelete1MouseClicked

    private void btn_gymDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gymDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gymDelete1ActionPerformed

    private void btn_updateGym1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateGym1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateGym1MouseClicked

    private void btn_updateGym1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateGym1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateGym1ActionPerformed

    private void btn_resetFilterGym1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetFilterGym1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterGym1MouseClicked

    private void btn_resetFilterGym1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFilterGym1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterGym1ActionPerformed

    private void txt_filterAddressGymTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterAddressGymTable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterAddressGymTable1ActionPerformed

    private void txt_filterNameGymTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterNameGymTable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterNameGymTable1ActionPerformed

    private void btn_confirmFilterGymtbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmFilterGymtbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmFilterGymtbl1MouseClicked

    private void btn_confirmFilterGymtbl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmFilterGymtbl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirmFilterGymtbl1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmFilterGymtbl1;
    public javax.swing.JButton btn_gymDelete1;
    private javax.swing.JButton btn_gymInsert1;
    private javax.swing.JButton btn_resetFilterGym1;
    public javax.swing.JButton btn_updateGym1;
    public javax.swing.JTable jtable_gym1;
    private javax.swing.JLabel label_AddressFilterGymtbl1;
    private javax.swing.JLabel label_NameFilterGymtbl1;
    private javax.swing.JLabel label_gymTable1;
    public javax.swing.JScrollPane scrlpn_tableGym1;
    private javax.swing.JTextField txt_filterAddressGymTable1;
    private javax.swing.JTextField txt_filterNameGymTable1;
    // End of variables declaration//GEN-END:variables
}
