/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author mhpolymath
 */
public class memeber_panel extends javax.swing.JPanel {

    /**
     * Creates new form memeber_panel
     */
    public memeber_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlpn_tableMember = new javax.swing.JScrollPane();
        jtable_member = new javax.swing.JTable();
        label_membersTable = new javax.swing.JLabel();
        btn_memberInsert = new javax.swing.JButton();
        btn_memberDelete = new javax.swing.JButton();
        btn_updateMember = new javax.swing.JButton();
        btn_resetFilterMember = new javax.swing.JButton();
        txt_filterLastNameMemberTable = new javax.swing.JTextField();
        txt_filterFirstNameMemberTable = new javax.swing.JTextField();
        label_firstNameFiltermembertbl = new javax.swing.JLabel();
        label_lastNameFiltermembertbl = new javax.swing.JLabel();
        btn_confirmFilterMembertbl = new javax.swing.JButton();

        jtable_member.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jtable_member.setModel(new MemberTable().loadTable()
        );
        jtable_member.setDefaultEditor(Object.class,null);
        setupTableListener();
        jtable_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_memberMouseClicked(evt);
            }
        });
        scrlpn_tableMember.setViewportView(jtable_member);

        label_membersTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_membersTable.setText("Members Table");

        btn_memberInsert.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_memberInsert.setText("Insert");
        btn_memberInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memberInsertMouseClicked(evt);
            }
        });
        btn_memberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberInsertActionPerformed(evt);
            }
        });

        btn_memberDelete.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_memberDelete.setText("Delete");
        btn_memberDelete.setEnabled(false);
        btn_memberDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memberDeleteMouseClicked(evt);
            }
        });
        btn_memberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberDeleteActionPerformed(evt);
            }
        });

        btn_updateMember.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_updateMember.setText("Update");
        btn_updateMember.setEnabled(false);
        btn_updateMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMemberMouseClicked(evt);
            }
        });
        btn_updateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateMemberActionPerformed(evt);
            }
        });

        btn_resetFilterMember.setText("Reset Filter");
        btn_resetFilterMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetFilterMemberMouseClicked(evt);
            }
        });
        btn_resetFilterMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFilterMemberActionPerformed(evt);
            }
        });

        txt_filterLastNameMemberTable.setToolTipText("Enter last name");
        txt_filterLastNameMemberTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterLastNameMemberTableActionPerformed(evt);
            }
        });

        txt_filterFirstNameMemberTable.setToolTipText("Enter first name");
        txt_filterFirstNameMemberTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterFirstNameMemberTableActionPerformed(evt);
            }
        });

        label_firstNameFiltermembertbl.setText("First Name");

        label_lastNameFiltermembertbl.setText("Last Name");

        btn_confirmFilterMembertbl.setText("Filter");
        btn_confirmFilterMembertbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmFilterMembertblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_memberDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_memberInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_updateMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_membersTable)
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrlpn_tableMember, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filterFirstNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_firstNameFiltermembertbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filterLastNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_confirmFilterMembertbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_resetFilterMember))
                            .addComponent(label_lastNameFiltermembertbl))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstNameFiltermembertbl)
                    .addComponent(label_lastNameFiltermembertbl))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filterLastNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFilterMember)
                    .addComponent(txt_filterFirstNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmFilterMembertbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_membersTable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_memberInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlpn_tableMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_memberDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_updateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_memberMouseClicked

    }//GEN-LAST:event_jtable_memberMouseClicked

    private void btn_memberInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memberInsertMouseClicked

    }//GEN-LAST:event_btn_memberInsertMouseClicked

    private void btn_memberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberInsertActionPerformed
        clearInsertFormTextFields();
        jframe_insertMember.setVisible(true);
    }//GEN-LAST:event_btn_memberInsertActionPerformed

    private void btn_memberDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memberDeleteMouseClicked
        if(!btn_memberDelete.isEnabled())
        return;
        int selectedRow = jtable_member.getSelectedRow();
        if(selectedRow == -1)
        return;

        Integer memberID = (Integer)jtable_member.getValueAt(selectedRow, 0);

        try{
            int result = new MemberTable().delete(new Member(memberID));
            if(result == 1){
                DatabaseOperation.showSuccessMessage(panel_member,"Member deleted successfully.");
                jtable_member.setModel(new MemberTable().loadTable());

            }
            else
            DatabaseOperation.showErrorMessage(panel_member,"Delete failed.");
        }
        catch(java.sql.SQLException e){
            DatabaseOperation.showErrorMessage(panel_member,e.getMessage());
        }
    }//GEN-LAST:event_btn_memberDeleteMouseClicked

    private void btn_memberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_memberDeleteActionPerformed

    private void btn_updateMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMemberMouseClicked
        if(!btn_updateMember.isEnabled())
        return;
        if(jtable_member.getSelectedRow() == -1)
        return;

        fillUpdateFieldsWithOldData();
        jframe_updateMember.setVisible(true);
    }//GEN-LAST:event_btn_updateMemberMouseClicked

    private void btn_updateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateMemberActionPerformed

    private void btn_resetFilterMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetFilterMemberMouseClicked
        jtable_member.setModel(new MemberTable().loadTable());
        txt_filterFirstNameMemberTable.setText("");
        txt_filterLastNameMemberTable.setText("");
    }//GEN-LAST:event_btn_resetFilterMemberMouseClicked

    private void btn_resetFilterMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFilterMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterMemberActionPerformed

    private void txt_filterLastNameMemberTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterLastNameMemberTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterLastNameMemberTableActionPerformed

    private void txt_filterFirstNameMemberTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterFirstNameMemberTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterFirstNameMemberTableActionPerformed

    private void btn_confirmFilterMembertblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmFilterMembertblMouseClicked
        String fname = txt_filterFirstNameMemberTable.getText();
        String lname = txt_filterLastNameMemberTable.getText();

        jtable_member.setModel(new MemberTable().selectByMemberName(new Member(null,fname,lname,null)));

    }//GEN-LAST:event_btn_confirmFilterMembertblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmFilterMembertbl;
    public javax.swing.JButton btn_memberDelete;
    private javax.swing.JButton btn_memberInsert;
    private javax.swing.JButton btn_resetFilterMember;
    public javax.swing.JButton btn_updateMember;
    public javax.swing.JTable jtable_member;
    private javax.swing.JLabel label_firstNameFiltermembertbl;
    private javax.swing.JLabel label_lastNameFiltermembertbl;
    private javax.swing.JLabel label_membersTable;
    public javax.swing.JScrollPane scrlpn_tableMember;
    private javax.swing.JTextField txt_filterFirstNameMemberTable;
    private javax.swing.JTextField txt_filterLastNameMemberTable;
    // End of variables declaration//GEN-END:variables
}
