/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.DatabaseOperation;
import entities.Member;
import javax.swing.JComboBox;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tables.MemberTable;

/**
 *
 * @author OAK-1
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframe_insertMember = new javax.swing.JFrame();
        panel_ofFrame_insertMemberForm = new javax.swing.JPanel();
        txt_insert_memberID = new javax.swing.JTextField();
        label_memberID = new javax.swing.JLabel();
        btn_insertMemberConfirm = new javax.swing.JButton();
        txt_insert_memberFname = new javax.swing.JTextField();
        txt_insert_memberLname = new javax.swing.JTextField();
        txt_insert_memberPhone = new javax.swing.JTextField();
        label_memberFname = new javax.swing.JLabel();
        label_memberLname = new javax.swing.JLabel();
        label_memberPhone = new javax.swing.JLabel();
        jframe_updateMember = new javax.swing.JFrame();
        panel_ofFrame_updateMemberForm = new javax.swing.JPanel();
        txt_update_memberFname = new javax.swing.JTextField();
        txt_update_memberLname = new javax.swing.JTextField();
        txt_update_memberPhone = new javax.swing.JTextField();
        label_memberFname1 = new javax.swing.JLabel();
        label_memberLname1 = new javax.swing.JLabel();
        label_memberPhone1 = new javax.swing.JLabel();
        txt_update_memberID = new javax.swing.JTextField();
        label_memberID1 = new javax.swing.JLabel();
        btn_updateMemberConfirm = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_member = new javax.swing.JPanel();
        scrlpn_tableMember = new javax.swing.JScrollPane();
        jtable_member = new javax.swing.JTable();
        label_membersTable = new javax.swing.JLabel();
        btn_memberInsert = new javax.swing.JButton();
        btn_memberDelete = new javax.swing.JButton();
        btn_updateMember = new javax.swing.JButton();
        btn_resetFilterMember = new javax.swing.JButton();
        txt_filterLastNameMemberTable = new javax.swing.JTextField();
        txt_filterFirstNameMemberTable = new javax.swing.JTextField();
        label_firstNameFiltermembertbl = new javax.swing.JLabel();
        label_lastNameFiltermembertbl = new javax.swing.JLabel();
        btn_confirmFilterMembertbl = new javax.swing.JButton();
        panel_gym = new javax.swing.JPanel();

        jframe_insertMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jframe_insertMember.setTitle("Insert");
        jframe_insertMember.setAlwaysOnTop(true);
        jframe_insertMember.setMinimumSize(new java.awt.Dimension(600, 600));
        jframe_insertMember.setResizable(false);
        jframe_insertMember.setVisible(false);

        panel_ofFrame_insertMemberForm.setMinimumSize(new java.awt.Dimension(600, 600));
        panel_ofFrame_insertMemberForm.setPreferredSize(new java.awt.Dimension(600, 600));

        txt_insert_memberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_insert_memberIDActionPerformed(evt);
            }
        });

        label_memberID.setText("ID");

        btn_insertMemberConfirm.setText("Submit");
        btn_insertMemberConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_insertMemberConfirmMouseClicked(evt);
            }
        });
        btn_insertMemberConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertMemberConfirmActionPerformed(evt);
            }
        });

        txt_insert_memberFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_insert_memberFnameActionPerformed(evt);
            }
        });

        txt_insert_memberLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_insert_memberLnameActionPerformed(evt);
            }
        });

        txt_insert_memberPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_insert_memberPhoneActionPerformed(evt);
            }
        });

        label_memberFname.setText("First Name");

        label_memberLname.setText("Last Name");

        label_memberPhone.setText("Phone Number");

        javax.swing.GroupLayout panel_ofFrame_insertMemberFormLayout = new javax.swing.GroupLayout(panel_ofFrame_insertMemberForm);
        panel_ofFrame_insertMemberForm.setLayout(panel_ofFrame_insertMemberFormLayout);
        panel_ofFrame_insertMemberFormLayout.setHorizontalGroup(
            panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                                .addComponent(txt_insert_memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_insert_memberFname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(label_memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(label_memberFname, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_insert_memberLname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_memberLname, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_insert_memberPhone)
                            .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                                .addComponent(label_memberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btn_insertMemberConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
        panel_ofFrame_insertMemberFormLayout.setVerticalGroup(
            panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ofFrame_insertMemberFormLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_memberID)
                    .addComponent(label_memberFname)
                    .addComponent(label_memberLname)
                    .addComponent(label_memberPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ofFrame_insertMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_insert_memberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_insert_memberFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_insert_memberLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_insert_memberPhone))
                .addGap(82, 82, 82)
                .addComponent(btn_insertMemberConfirm)
                .addGap(453, 453, 453))
        );

        javax.swing.GroupLayout jframe_insertMemberLayout = new javax.swing.GroupLayout(jframe_insertMember.getContentPane());
        jframe_insertMember.getContentPane().setLayout(jframe_insertMemberLayout);
        jframe_insertMemberLayout.setHorizontalGroup(
            jframe_insertMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ofFrame_insertMemberForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jframe_insertMemberLayout.setVerticalGroup(
            jframe_insertMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_insertMemberLayout.createSequentialGroup()
                .addComponent(panel_ofFrame_insertMemberForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jframe_updateMember.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jframe_updateMember.setTitle("Update");
        jframe_updateMember.setAlwaysOnTop(true);
        jframe_updateMember.setMinimumSize(new java.awt.Dimension(600, 600));
        jframe_updateMember.setVisible(false);

        txt_update_memberFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_memberFnameActionPerformed(evt);
            }
        });

        txt_update_memberLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_memberLnameActionPerformed(evt);
            }
        });

        txt_update_memberPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_memberPhoneActionPerformed(evt);
            }
        });

        label_memberFname1.setText("First Name");

        label_memberLname1.setText("Last Name");

        label_memberPhone1.setText("Phone Number");

        txt_update_memberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_memberIDActionPerformed(evt);
            }
        });

        label_memberID1.setText("ID");

        btn_updateMemberConfirm.setText("Submit");
        btn_updateMemberConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMemberConfirmMouseClicked(evt);
            }
        });
        btn_updateMemberConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateMemberConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ofFrame_updateMemberFormLayout = new javax.swing.GroupLayout(panel_ofFrame_updateMemberForm);
        panel_ofFrame_updateMemberForm.setLayout(panel_ofFrame_updateMemberFormLayout);
        panel_ofFrame_updateMemberFormLayout.setHorizontalGroup(
            panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                                .addComponent(txt_update_memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_update_memberFname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(label_memberID1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(label_memberFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_update_memberLname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_memberLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_update_memberPhone)
                            .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                                .addComponent(label_memberPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btn_updateMemberConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
        panel_ofFrame_updateMemberFormLayout.setVerticalGroup(
            panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ofFrame_updateMemberFormLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_memberID1)
                    .addComponent(label_memberFname1)
                    .addComponent(label_memberLname1)
                    .addComponent(label_memberPhone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ofFrame_updateMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_update_memberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_memberFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_memberLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_memberPhone))
                .addGap(82, 82, 82)
                .addComponent(btn_updateMemberConfirm)
                .addGap(453, 453, 453))
        );

        javax.swing.GroupLayout jframe_updateMemberLayout = new javax.swing.GroupLayout(jframe_updateMember.getContentPane());
        jframe_updateMember.getContentPane().setLayout(jframe_updateMemberLayout);
        jframe_updateMemberLayout.setHorizontalGroup(
            jframe_updateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ofFrame_updateMemberForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jframe_updateMemberLayout.setVerticalGroup(
            jframe_updateMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_ofFrame_updateMemberForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym Manager");
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panel_member.setMinimumSize(new java.awt.Dimension(800, 800));
        panel_member.setPreferredSize(new java.awt.Dimension(800, 800));
        panel_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_memberMouseClicked(evt);
            }
        });

        scrlpn_tableMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scrlpn_tableMember.setNextFocusableComponent(jtable_member);
        scrlpn_tableMember.setViewportView(jtable_member);

        jtable_member.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jtable_member.setModel(new MemberTable().loadTable()
        );
        jtable_member.setDefaultEditor(Object.class,null);
        setupTableListener();
        jtable_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_memberMouseClicked(evt);
            }
        });
        scrlpn_tableMember.setViewportView(jtable_member);

        label_membersTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_membersTable.setText("Members Table");

        btn_memberInsert.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_memberInsert.setText("Insert");
        btn_memberInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memberInsertMouseClicked(evt);
            }
        });
        btn_memberInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberInsertActionPerformed(evt);
            }
        });

        btn_memberDelete.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_memberDelete.setText("Delete");
        btn_memberDelete.setEnabled(false);
        btn_memberDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_memberDeleteMouseClicked(evt);
            }
        });
        btn_memberDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memberDeleteActionPerformed(evt);
            }
        });

        btn_updateMember.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_updateMember.setText("Update");
        btn_updateMember.setEnabled(false);
        btn_updateMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMemberMouseClicked(evt);
            }
        });
        btn_updateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateMemberActionPerformed(evt);
            }
        });

        btn_resetFilterMember.setText("Reset Filter");
        btn_resetFilterMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetFilterMemberMouseClicked(evt);
            }
        });
        btn_resetFilterMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFilterMemberActionPerformed(evt);
            }
        });

        txt_filterLastNameMemberTable.setToolTipText("Enter last name");
        txt_filterLastNameMemberTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterLastNameMemberTableActionPerformed(evt);
            }
        });

        txt_filterFirstNameMemberTable.setToolTipText("Enter first name");
        txt_filterFirstNameMemberTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterFirstNameMemberTableActionPerformed(evt);
            }
        });

        label_firstNameFiltermembertbl.setText("First Name");

        label_lastNameFiltermembertbl.setText("Last Name");

        btn_confirmFilterMembertbl.setText("Filter");
        btn_confirmFilterMembertbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmFilterMembertblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_memberLayout = new javax.swing.GroupLayout(panel_member);
        panel_member.setLayout(panel_memberLayout);
        panel_memberLayout.setHorizontalGroup(
            panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_memberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_memberDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(btn_memberInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_updateMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_memberLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_memberLayout.createSequentialGroup()
                                .addComponent(label_membersTable)
                                .addGap(221, 221, 221))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_memberLayout.createSequentialGroup()
                                .addComponent(scrlpn_tableMember, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))))
                    .addGroup(panel_memberLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_filterFirstNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_firstNameFiltermembertbl))
                        .addGap(18, 18, 18)
                        .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_memberLayout.createSequentialGroup()
                                .addComponent(txt_filterLastNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btn_confirmFilterMembertbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_resetFilterMember))
                            .addComponent(label_lastNameFiltermembertbl))
                        .addGap(0, 335, Short.MAX_VALUE))))
        );
        panel_memberLayout.setVerticalGroup(
            panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_memberLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstNameFiltermembertbl)
                    .addComponent(label_lastNameFiltermembertbl))
                .addGap(2, 2, 2)
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filterLastNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFilterMember)
                    .addComponent(txt_filterFirstNameMemberTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_confirmFilterMembertbl))
                .addGap(29, 29, 29)
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_membersTable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_memberInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_memberLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlpn_tableMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_memberLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_memberDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_updateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Member", panel_member);

        javax.swing.GroupLayout panel_gymLayout = new javax.swing.GroupLayout(panel_gym);
        panel_gym.setLayout(panel_gymLayout);
        panel_gymLayout.setHorizontalGroup(
            panel_gymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        panel_gymLayout.setVerticalGroup(
            panel_gymLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gym", panel_gym);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void clearInsertFormTextFields(){
       txt_insert_memberID.setText("");
       txt_insert_memberFname.setText("");
       txt_insert_memberLname.setText("");
       txt_insert_memberPhone.setText("");
   }
   
   private void fillUpdateFieldsWithOldData(){
       int selectedRow = jtable_member.getSelectedRow();
       if(selectedRow == -1)
            return;
       
       Integer ID = (Integer)jtable_member.getValueAt(selectedRow,0);
       String fname = (String)jtable_member.getValueAt(selectedRow,1);
       String lname = (String)jtable_member.getValueAt(selectedRow,2);
       String phone = (String)jtable_member.getValueAt(selectedRow,3);
       
       txt_update_memberID.setText(String.valueOf(ID));
       txt_update_memberFname.setText(fname);
       txt_update_memberLname.setText(lname);
       txt_update_memberPhone.setText(phone);
   }
    private void btn_memberInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberInsertActionPerformed
        clearInsertFormTextFields();
        jframe_insertMember.setVisible(true);
    }//GEN-LAST:event_btn_memberInsertActionPerformed
    
    private void btn_memberInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memberInsertMouseClicked

    }//GEN-LAST:event_btn_memberInsertMouseClicked

    private void txt_insert_memberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_insert_memberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_insert_memberIDActionPerformed

    private void btn_insertMemberConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertMemberConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_insertMemberConfirmActionPerformed

    private void txt_insert_memberFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_insert_memberFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_insert_memberFnameActionPerformed

    private void txt_insert_memberLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_insert_memberLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_insert_memberLnameActionPerformed

    private void txt_insert_memberPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_insert_memberPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_insert_memberPhoneActionPerformed

    private void btn_insertMemberConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_insertMemberConfirmMouseClicked
        Integer memberID = null;
        try {
            memberID = Integer.parseInt(txt_insert_memberID.getText());

        } catch (NumberFormatException e) {
            DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm, "Invalid ID entered.");
            jframe_insertMember.dispose();
            return;
        }
        String fname = txt_insert_memberFname.getText();
        if(fname.isEmpty())
                fname = null;
        String lname = txt_insert_memberLname.getText();
        if(lname.isEmpty())
                lname = null;
        String phone = txt_insert_memberPhone.getText();
        if(phone.isEmpty())
                phone = null;
        Member insertedMember = new Member(memberID, fname, lname, phone);

        try {
            int result = new MemberTable().insert(insertedMember);
            if(result == 1){
                    DatabaseOperation.showSuccessMessage(panel_ofFrame_insertMemberForm, "Insertion Successful.");
                    jtable_member.setModel(new MemberTable().loadTable());
            }
            else 
                DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm,"Insertion failed.");
                
        }catch(java.sql.SQLException e){
            DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm,e.getMessage());
        }
        
       jframe_insertMember.dispose();
    }//GEN-LAST:event_btn_insertMemberConfirmMouseClicked

    private void btn_memberDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memberDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_memberDeleteActionPerformed

    private void jtable_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_memberMouseClicked
   
   
    }//GEN-LAST:event_jtable_memberMouseClicked

    private void panel_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_memberMouseClicked
        jtable_member.clearSelection();
        panel_member.requestFocusInWindow();
    }//GEN-LAST:event_panel_memberMouseClicked
    
    private void btn_memberDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memberDeleteMouseClicked
        if(!btn_memberDelete.isEnabled())
               return;
        int selectedRow = jtable_member.getSelectedRow();
       if(selectedRow == -1)
            return;
       
       Integer memberID = (Integer)jtable_member.getValueAt(selectedRow, 0);
       
       try{
           int result = new MemberTable().delete(new Member(memberID));
           if(result == 1){
                DatabaseOperation.showSuccessMessage(panel_member,"Member deleted successfully.");
                jtable_member.setModel(new MemberTable().loadTable());
                
           }
           else
               DatabaseOperation.showErrorMessage(panel_member,"Delete failed.");
       }
       catch(java.sql.SQLException e){
           DatabaseOperation.showErrorMessage(panel_member,e.getMessage());
       }
    }//GEN-LAST:event_btn_memberDeleteMouseClicked

    private void btn_updateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateMemberActionPerformed

    private void txt_update_memberFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_memberFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_memberFnameActionPerformed

    private void txt_update_memberLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_memberLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_memberLnameActionPerformed

    private void txt_update_memberPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_memberPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_memberPhoneActionPerformed

    private void txt_update_memberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_memberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_memberIDActionPerformed

    private void btn_updateMemberConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMemberConfirmMouseClicked
        if(jtable_member.getSelectedRow() == -1)
                return;
        Member oldData = new Member((Integer)jtable_member.getValueAt(jtable_member.getSelectedRow(),0));
        Integer memberID = null;
        try {
            memberID = Integer.parseInt(txt_update_memberID.getText());

        } catch (NumberFormatException e) {
            DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm, "Invalid ID entered.");
            jframe_updateMember.dispose();
            return;
        }
        String fname = txt_update_memberFname.getText();
        if(fname.isEmpty())
                fname = null;
        String lname = txt_update_memberLname.getText();
        if(lname.isEmpty())
                lname = null;
        String phone = txt_update_memberPhone.getText();
        if(phone.isEmpty())
                phone = null;
        Member newData = new Member(memberID, fname, lname, phone);

        try {
            int result = new MemberTable().update(oldData,newData);
            if(result == 1){
                    DatabaseOperation.showSuccessMessage(panel_ofFrame_insertMemberForm, "Update successful.");
                    jtable_member.setModel(new MemberTable().loadTable());
            }
            else 
                DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm,"Update failed.");
                
        }catch(java.sql.SQLException e){
            DatabaseOperation.showErrorMessage(panel_ofFrame_insertMemberForm,e.getMessage());
        }
        
       jframe_updateMember.dispose();
        
    }//GEN-LAST:event_btn_updateMemberConfirmMouseClicked

    private void btn_updateMemberConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateMemberConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateMemberConfirmActionPerformed

    private void btn_updateMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMemberMouseClicked
       if(!btn_updateMember.isEnabled())
            return;
       if(jtable_member.getSelectedRow() == -1)
            return;
       
       fillUpdateFieldsWithOldData();
       jframe_updateMember.setVisible(true);
    }//GEN-LAST:event_btn_updateMemberMouseClicked

    private void btn_resetFilterMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetFilterMemberMouseClicked
       jtable_member.setModel(new MemberTable().loadTable());
       txt_filterFirstNameMemberTable.setText("");
       txt_filterLastNameMemberTable.setText("");
    }//GEN-LAST:event_btn_resetFilterMemberMouseClicked

    private void txt_filterLastNameMemberTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterLastNameMemberTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterLastNameMemberTableActionPerformed

    private void txt_filterFirstNameMemberTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterFirstNameMemberTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterFirstNameMemberTableActionPerformed

    private void btn_resetFilterMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFilterMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetFilterMemberActionPerformed

    private void btn_confirmFilterMembertblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmFilterMembertblMouseClicked
        String fname = txt_filterFirstNameMemberTable.getText();
        String lname = txt_filterLastNameMemberTable.getText();
        
        jtable_member.setModel(new MemberTable().selectByMemberName(new Member(null,fname,lname,null)));
        
    }//GEN-LAST:event_btn_confirmFilterMembertblMouseClicked
    public void setupTableListener() {
    // Get the selection model of the table
    ListSelectionModel selectionModel = jtable_member.getSelectionModel();

    // Add the listener to the selection model
    selectionModel.addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            // Check if a row is selected
            if (jtable_member.getSelectedRow() != -1) {
                // Enable the delete button if a row is selected
                btn_memberDelete.setEnabled(true);
                btn_updateMember.setEnabled(true);
            } else {
                // Disable the delete button if no row is selected
                btn_memberDelete.setEnabled(false);
                btn_updateMember.setEnabled(false);
            }
        }
    });
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MainFrame().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmFilterMembertbl;
    private javax.swing.JButton btn_insertMemberConfirm;
    public javax.swing.JButton btn_memberDelete;
    private javax.swing.JButton btn_memberInsert;
    private javax.swing.JButton btn_resetFilterMember;
    public javax.swing.JButton btn_updateMember;
    private javax.swing.JButton btn_updateMemberConfirm;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFrame jframe_insertMember;
    private javax.swing.JFrame jframe_updateMember;
    public javax.swing.JTable jtable_member;
    private javax.swing.JLabel label_firstNameFiltermembertbl;
    private javax.swing.JLabel label_lastNameFiltermembertbl;
    private javax.swing.JLabel label_memberFname;
    private javax.swing.JLabel label_memberFname1;
    private javax.swing.JLabel label_memberID;
    private javax.swing.JLabel label_memberID1;
    private javax.swing.JLabel label_memberLname;
    private javax.swing.JLabel label_memberLname1;
    private javax.swing.JLabel label_memberPhone;
    private javax.swing.JLabel label_memberPhone1;
    private javax.swing.JLabel label_membersTable;
    private javax.swing.JPanel panel_gym;
    public javax.swing.JPanel panel_member;
    private javax.swing.JPanel panel_ofFrame_insertMemberForm;
    private javax.swing.JPanel panel_ofFrame_updateMemberForm;
    public javax.swing.JScrollPane scrlpn_tableMember;
    private javax.swing.JTextField txt_filterFirstNameMemberTable;
    private javax.swing.JTextField txt_filterLastNameMemberTable;
    private javax.swing.JTextField txt_insert_memberFname;
    private javax.swing.JTextField txt_insert_memberID;
    private javax.swing.JTextField txt_insert_memberLname;
    private javax.swing.JTextField txt_insert_memberPhone;
    private javax.swing.JTextField txt_update_memberFname;
    private javax.swing.JTextField txt_update_memberID;
    private javax.swing.JTextField txt_update_memberLname;
    private javax.swing.JTextField txt_update_memberPhone;
    // End of variables declaration//GEN-END:variables
}
